### ISSUE TITLE
[W3C & WAI] evaluation/testing coverage

### ISSUE THREAD

**Issue by shawna-slh** [w3c/accessibility-intro#1]
Current draft does not have a separate section on Evaluation / Testing. It does have:
* [How section](https://w3c.github.io/accessibility-intro/#doit) includes link to Easy Checks
* [Learn More section](https://w3c.github.io/accessibility-intro/#learnmore) has linked "<a href="https://www.w3.org/WAI/eval">testing/evaluation</a>"

We could include it in the [Use It section](https://w3c.github.io/accessibility-intro/#useitrhs).

Is this sufficient coverage? Do we want to add more -- either sentences, links, additional section?

**Comment by nrhsinclair** [comment]
I think testing/evaluation could use a bullet point and description directly under Easy Checks in How section (looks as though it should also include some revision).

**Comment by shawna-slh** [comment]
I'm not sure what you are suggesting. Would you provide specific wording suggestion. Thanks!

**Comment by nrhsinclair** [comment]
I think testing / evaluation could have a bullet point similar to below since there is a good bit of helpful information on selecting evaluation tools and conducting testing (however, there is so much information it looks as though that section is also a good candidate for editing and revising). 
Here are places to start:
Accessibility Principles — introduces accessibility requirements and provides references international web accessibility standards.
Easy Checks - A First Review — helps you start to test the accessibility of a web page and understand some common accessibility barriers.
**Testing / Evaluation - Web accessibility evaluation tools can significantly reduce the time and effort required to carry out evaluations. This resource provides guidance on evaluation tools and approaches that can be useful in testing the accessibility of web pages.**
Tips for Getting Started — introduces some basic considerations for designing, writing, and developing for web accessibility.

**Comment by notabene** [comment]
+1 with @nrhsinclair 's suggestion

<del>(side note: I'm a bit puzzled by the "Use it" section, too. What is its purpose? Is it a TLDR synthetic list of links that are provided elsewhere in the document because you fear they are too hard to find?)</del> (oops sorry, comment moved to [proper issue](https://github.com/w3c/accessibility-intro/issues/2))

**Comment by shawna-slh** [comment]
Thank you for the specific suggestion, Norah!

I propose that we leave it as is for now, and when ready to launch the redesigned WAI website, see if there is a better way to integrate evaluation, based on what we do with the redesign.
