### ISSUE TITLE
[W3C] Consistency/inconsistency of bolding

### ISSUE THREAD

**Issue by kakinney** [w3c/accessibility-intro#11]
I think the content of the page is spot on.  Its a wonderful introduction to accessibility.  However, the few bold sentences (or partially bold sentences) under the intro and Why is throwing me off.  Is it just because you're trying to make the case most for the Why of accessibility.  And if so, then I think that "Accessibility also benefits people without disabilities" needs to be bolded too.  

Nothing else is bolded/strong in the What or How which makes it seem like those things aren't as important as the Why.

**Comment by shawna-slh** [comment]
For some people, bold helps things stand out, especially when skimming on the Web.

Indeed, those are the things we most wanted to stand out up front.

While bolding "Accessibility also benefits people without disabilities" would increase consistency, we did not want that point to stand out as much -- which is why it wasn't bolded.

Correct that their weren't clear specific points in the other sections that we wanted to stand out with bold.

I'm inclined to leave it as is... although probably could be talked into taking all the bold out of that section if someone felt strongly. Feel free to re-open if you want to discuss. :-)
